version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    reviewers:
      - "@Shopify/functions-dependabot-reviewers"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    groups:
      minor-versions:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "@Shopify/functions-dependabot-reviewers"
    schedule:
      interval: "weekly"
