name: shopify-function-wasm-api

type: rust

up:
  - rust
  - custom:
      name: Install Insta (snapshot testing) for Rust
      meet: cargo install cargo-insta
      met?: cargo install --list | grep cargo-insta

commands:
  test:
    run: |
      cargo test
      cargo test --examples
  style:
    run: |
      cargo fmt
      cargo clippy --all-features -- -D warnings
      cargo clippy --target wasm32-wasip1 --all-features --workspace --exclude shopify_function_wasm_api_trampoline --exclude integration_tests -- -D warnings
      cargo clippy --tests --all-features
      cargo clippy --benches --all-features
      cargo clippy --examples --all-features
      cargo clippy --examples --target wasm32-wasip1 --all-features
  build:
    run: cargo build --release --all-features

check:
  test: /opt/dev/bin/dev test
  style: /opt/dev/bin/dev style
  build: /opt/dev/bin/dev build
