[package]
name = "shopify_function_wasm_api"
version = "0.0.1"
edition = "2021"

[dependencies]
shopify_function_wasm_api_core = { path = "../core", version = "0.0.1" }
thiserror = "2.0"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "echo"
path = "examples/echo.rs"
