[package]
name = "shopify_function_wasm_api"
version = "0.0.1"
edition = "2021"

[dependencies]
shopify_function_wasm_api_core = { path = "../core", version = "0.0.1" }
thiserror = "2.0"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
serde_json = "1.0.140"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "echo"
path = "examples/echo.rs"

[[example]]
name = "serialization"
path = "examples/serialization.rs"
