[package]
name = "shopify_function_wasm_api"
version = "0.1.0"
edition = "2021"

[dependencies]
shopify_function_wasm_api_core = { path = "../core", version = "0.1.0" }

[build-dependencies]
walrus = "0.23.3"

[[example]]
name = "simple"
path = "examples/simple.rs"
